version: '3.8'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=exploreWM_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPsword

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=exploreWM_main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPsword

  stats-server:
    build: stats-service/stats-server
    image: axoryl/explore-with-me_stats:v1
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWM_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPsword

  ewm-service:
    build: main-service
    image: axoryl/explore-with-me_main:v1
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/exploreWM_main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPsword
